New branch two
dcavinder/park_search pull request #15
Opened 2022-10-02 23:15 UTC by Mntnbassfan

2022-10-02 23:32 UTC, rdahltorp requested changes
Looking super good! Just a couple of things: 

- For the h1 and i on lines 10 and 11, we can put those in the body and put them in a header element. Pretty much where they were before just enclosed in a header element. 
- We can actually remove lines 20-24 since that info is in the form section that you added.
- We can uncomment-out line 28 so the button is included.
- We can remove lines 31 and 32 since the home icon is in the header now.

2022-10-02 23:38 UTC, dcavinder commented
The script ref at the bottom should be script.js as well instead of homepage.js

2022-10-03 00:12 UTC, dcavinder approved these changes

2022-10-03 00:15 UTC, rdahltorp reviewed
Looks good!

2022-10-03 00:15 UTC, rdahltorp approved these changes

2022-10-03 00:15 UTC, merged